config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }, :skip => [:sessions, :registrations]
  as :user do
    get    'signup'  => 'registrations#new',       :as => :new_user_registration
    post   'signup'  => 'registrations#create',    :as => :user_registration
    get    'signin'  => 'devise/sessions#new',     :as => :new_user_session
    post   'signin'  => 'devise/sessions#create',  :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users, only: [ :show, :index ] do
    resources :friendships, only: [ :index ]
  end

  resources :friendships, only: [ :create, :update, :destroy ]
  
  get 'friendship/requests' => 'friendships#requests'

  resources :posts, only: [ :index, :create, :show ] do
    resources :likes, only: [ :create ]
    resources :comments, only: [ :create ]
    resource  :like, only: [ :destroy ]
  end

  resources :comments, only: [] do
    resources :likes, only: [ :create ]
    resource  :like, only: [ :destroy ]
  end
  
  resource :profile, only: [ :edit, :update ]

  root 'posts#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # matcher taken from: http://www.regular-expressions.info/email.html
  EMAIL_MATCHER = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
  
  validates :password, length: { minimum: 8, maximum: 50 }
  validates :email,    length: { maximum: 50 }, format: { with: EMAIL_MATCHER }
  
  has_many :initiated_friendships,  foreign_key: :user_1_id, class: Friendship
  has_many :friendships_invited_to, foreign_key: :user_2_id, class: Friendship
  
  has_many :invited_users,    through: :initiated_friendships,  source: :user_2, class: User
  has_many :users_invited_by, through: :friendships_invited_to, source: :user_1, class: User
  
  has_many :posts
  has_many :comments

  has_many :likes

  has_one :profile

  after_create :build_empty_profile

  default_scope -> { order('id ASC') }

  def friendships
    Friendship.where('user_1_id=:id OR user_2_id=:id', id: id)
  end
  
  def friends
    User.joins("JOIN friendships f ON (users.id = f.user_1_id OR users.id = f.user_2_id)")
        .where("users.id <> :id AND (f.user_1_id = :id OR f.user_2_id = :id)", id: id)
        .where("f.user_1_status = 'active' AND f.user_2_status = 'active'")
  end

  def potential_friends
    related = User.joins("JOIN friendships f ON (users.id = f.user_1_id OR users.id = f.user_2_id)")
              .where("(f.user_1_id = :id OR f.user_2_id = :id)", id: id).uniq.ids
    User.where.not(id: related)
  end
  
  def friend_requests
    friendships_invited_to.where("user_2_status='pending'")
  end
  
  def sent_requests
    initiated_friendships.where("user_2_status='pending'")
  end
  
  def add_friend(user)
    Friendship.create(user_1: self, user_2: user, user_1_status: 'active', user_2_status: 'pending')
  end
  
  def friend?(other)
    ids = { id_1: self.id, id_2: other.id }
    Friendship.where('user_1_id=:id_1 AND user_2_id=:id_2 OR user_1_id=:id_2 AND user_2_id=:id_1', ids).first
  end
  
  def addable?(other)
    self != other && !other.friend?(self)
  end
  
  def timeline
    Post.where(user_id: friends.ids << id).includes(:user, :comments, :likes).order('created_at DESC')
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.find_by(provider: access_token.provider, uid: access_token.uid)
    if user
      return user
    else
      registered_user = User.find_by_email(access_token.info.email)
      if registered_user
        return registered_user
      else
        user = User.create!(provider: access_token.provider, email: data["email"], uid: access_token.uid ,
                            password: Devise.friendly_token[0,20])
        UserMailer.welcome_email(user).deliver unless user.invalid?
        user
      end
    end
  end
  
  private

    def build_empty_profile
      Profile.create!(user: self)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @potential_friends = current_user.potential_friends.paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @user  = User.find(params[:id])
    @posts = @user.posts.includes(:likes)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_buttons.html.haml
- if current_user.addable?(@user)
  = button_to "Add Friend", controller: "friendships", action: "create", method: :post, friend_id: @user.id
- elsif friendship = current_user.friend?(@user)
  = button_to "Cancel Friendship", friendship_path(friendship), method: :delete

app/views/users/_notifications.html.haml
- if current_user
  %p
    = link_to "You have #{pluralize(current_user.friend_requests.count, "friend request")}", friendship_requests_path

app/views/users/index.html.haml
%h1 Find friend

%ul
  - @potential_friends.each do |f|
    %li
      = gravatar_for(f)
      = link_to f.email, f
      = button_to "Add Friend", controller: "friendships", action: "create", method: :post, friend_id: f.id
      %br

= will_paginate @potential_friends

app/views/users/show.html.haml
%h1= @user.email

= render partial: 'friend_buttons'

- if current_user == @user
  = link_to "Edit profile", edit_profile_path

= gravatar_for(@user)

%table
  %tr
    %th About me
    %td= @user.profile.about_me
  %tr
    %th Gender
    %td= @user.profile.gender
  %tr
    %th Age
    %td= @user.profile.age
  %tr
    %th City
    %td= @user.profile.city
  %tr
    %th Country
    %td= @user.profile.country
  %tr
    %th Work
    %td= @user.profile.work
  %tr
    %th Website
    %td= @user.profile.website

%ul
  - @posts.each do |post|
    %li
      = pluralize(post.likes_counter, "Like")
      - if post.liked_by?(current_user)
        = button_to "Unlike", post_like_path(post), method: :delete
      - else
        = button_to "Like", post_likes_path(post), method: :post
      
      = link_to post.content, post

%h2
  = link_to "Friends", user_friendships_path(@user)