config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }, :skip => [:sessions, :registrations]
  as :user do
    get    'signup'  => 'registrations#new',       :as => :new_user_registration
    post   'signup'  => 'registrations#create',    :as => :user_registration
    get    'signin'  => 'devise/sessions#new',     :as => :new_user_session
    post   'signin'  => 'devise/sessions#create',  :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users, only: [ :show, :index ] do
    resources :friendships, only: [ :index ]
  end

  resources :friendships, only: [ :create, :update, :destroy ]
  
  get 'friendship/requests' => 'friendships#requests'

  resources :posts, only: [ :index, :create, :show ] do
    resources :likes, only: [ :create ]
    resources :comments, only: [ :create ]
    resource  :like, only: [ :destroy ]
  end

  resources :comments, only: [] do
    resources :likes, only: [ :create ]
    resource  :like, only: [ :destroy ]
  end
  
  resource :profile, only: [ :edit, :update ]

  root 'posts#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base

  include LikesHelper
  
  default_scope { includes(:likers) }

  validates :content, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :comments

  has_many :likes, as: :likeable
  has_many :likers, through: :likes, source: :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = current_user.timeline.paginate(:page => params[:page], :per_page => 20)
    @post = current_user.posts.build
  end

  def create
    p = post_from_params
    if p.save
      flash[:notice] = "Your post has been successfully created!"
    else
      flash[:warning] = "Post creation failed!"
    end
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  private
  
    def post_from_params
      Post.new do |p|
        p.user_id = current_user.id
        p.content = params[:post][:content]
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_list_layout.html.haml
%li
  = yield
  %br

app/views/posts/_post.html.haml
%p= post.user.email

.post_likes
  = pluralize(post.likes_counter, "Like")
  - post.likers.each do |l|
    = link_to l.email, user_path(l)
  - if post.liked_by?(current_user)
    = button_to "Unlike", post_like_path(post), method: :delete
  - else
    = button_to "Like", post_likes_path(post), method: :post

= link_to(post) do
  %p= post.content

%p= distance_of_time_in_words(post.created_at, Time.now)

%ul
  - post.comments.each do |comment|
    %li
      .comment_likes
        = pluralize(comment.likes_counter, "Like")
        - comment.likers.each do |l|
          = link_to l.email, user_path(l)
        -if comment.liked_by?(current_user)
          = button_to "unlike", comment_like_path(comment), method: :delete
        - else
          = button_to "like", comment_likes_path(comment), method: :post

      = comment.content
      by
      = link_to comment.user.email, comment.user

app/views/posts/index.html.haml
%h2
  = link_to "Find more friends", users_path

= form_for(@post) do |f|
  = f.text_area :content
  = f.submit "Post!"

%ul
  = render partial: 'post', collection: @posts, layout: 'list_layout'

= will_paginate @posts

app/views/posts/show.html.haml
= render partial: 'post', locals: { post: @post }

= form_for([@post, @comment]) do |f|
  = f.text_area :content
  = f.submit "Add comment"