config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }, :skip => [:sessions, :registrations]
  as :user do
    get    'signup'  => 'registrations#new',       :as => :new_user_registration
    post   'signup'  => 'registrations#create',    :as => :user_registration
    get    'signin'  => 'devise/sessions#new',     :as => :new_user_session
    post   'signin'  => 'devise/sessions#create',  :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users, only: [ :show, :index ] do
    resources :friendships, only: [ :index ]
  end

  resources :friendships, only: [ :create, :update, :destroy ]
  
  get 'friendship/requests' => 'friendships#requests'

  resources :posts, only: [ :index, :create, :show ] do
    resources :likes, only: [ :create ]
    resources :comments, only: [ :create ]
    resource  :like, only: [ :destroy ]
  end

  resources :comments, only: [] do
    resources :likes, only: [ :create ]
    resource  :like, only: [ :destroy ]
  end
  
  resource :profile, only: [ :edit, :update ]

  root 'posts#index'
  

end

app/views/layouts/_navbar.html.haml
.navbar
  = link_to "facebook-clone", root_path
  = link_to "about", static_pages_about_path
  - if current_user
    = link_to current_user.email, user_path(current_user)
    = link_to "Sign out", destroy_user_session_path, method: :delete
  - else
    = link_to "Sign in", new_user_session_path
    = link_to "Sign up", new_user_registration_path
    = link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OdinFacebookClone
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: 'layouts/navbar'
    = render partial: 'users/notifications'

    - flash.each do |key, value|
      %div{ class: "flash-#{key}" }
        = value

    = yield